#!/bin/bash

# Sourim-Install-Scripts
# Copyright (C) 2024 r2team
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

show_err() {
    echo "err: $1"
    exit 1
}

TEMPDIR=`mktemp -d`
ROOTDIR="$PWD"
PRIMARYDEVICE=

cd $TEMPDIR

echo "Search primary device..."
while read line; do
    words=($line)

    [[ ${words[1]} == "/" ]] && PRIMARYDEVICE="${words[0]}"
done < /etc/fstab
if [[ -z $PRIMARYDEVICE ]]; then
    echo "Primary device is not defined in /etc/fstab!"
    exit 1
fi

echo "Generating busybox progs..."
mkdir -p bin dev media proc sys lib/modules
cp /bin/busybox bin/ || show_err "busybox missing in system"
for prog in `busybox --list`; do
    ln -s busybox bin/$prog || show_err "ln"
done

echo "Copying kernel modules..."
cp -r /lib/modules/* lib/modules/

cat > init << EOF
#!/bin/sh

modules_fs="cdrom crc32c libcrc32c isofs ext2 ext4 reiserfs xfs jfs nls_cp437 nls_iso8859-1 vfat msdos btrfs"
modules_usb="usb-storage hid-generic hid-apple hid-logitech-dj"
modules_ata="libata libahci ahci sata_promise sata_sil sata_svw sata_via sata_mv sata_nv sata_sil24 sata_sx4 sata_sis sata_uli sata_vsc sata_qstor sata_inic162x ata_piix pata_mpiix pata_pdc2027x pata_radisys pata_sil680 pata_rz1000 pata_cmd640 pata_efar pata_cmd64x pata_hpt366 pata_hpt37x pata_hpt3x3 pata_opti pata_optidma pata_it8213 pata_ninja32 pata_it821x pata_artop pata_cypress pata_serverworks pata_ns87410 pata_ns87415 pata_ali pata_amd pdc_adma ata_generic pata_atiixp pata_triflex pata_netcell pata_sch pata_sis pata_hpt3x2n pata_marvell pata_jmicron pata_via pata_sl82c105"
modules_firewire="core ohci sbp2"
modules_scsi="scsi_mod sr_mod sd_mod scsi_transport_fc scsi_transport_iscsi scsi_transport_sas scsi_transport_spi 3w-9xxx 3w-xxxx 53c700 BusLogic NCR53c406a a100u2w aacraid advansys aha152x aha1542 aha1740 aic79xx aic7xxx aic94xx arcmsr atp870u dc395x dmx3191d dpt_i2o dtc eata fdomain gdth hptiop in2000 initio ipr ips lpfc megaraid megaraid_mbox megaraid_sas nsp32 pas16 psi240i qla1280 qla2xxx qla4xxx qlogicfas qlogicfas408 seagate sim710 stex sym53c416 sym53c8xx t128 u14-34f ultrastor wd7000 mptsas mptspi hpsa hv_storvsc virtio_scsi vmw_pvscsi"

echo "Enabling modules..."
for mod in \$modules_fs \$modules_usb \$modules_ata \$modules_firewire \$modules_scsi; do
    modprobe \$mod > /dev/null 2>&1
done

err() {
    /bin/sh
    sleep 99999
}

mount -t devtmpfs none /dev || err
mount -t proc none /proc || err
mount -t sysfs none /sys || err
mount $PRIMARYDEVICE /media || err

exec switch_root /media /bin/init
EOF
chmod +x init

echo "Generating initramfs..."
find . -print0 | cpio --null -ov --format=newc | gzip -9 > /boot/initramfs || show_err "creating cpio image"

cd -

rm -rf $TEMPDIR